Feature/erc20 mintable local faucet
Shard-Labs/starknet-devnet pull request #143
Opened 2022-06-29 20:41 UTC by tabaktoni

## Usage related changes

- Resolve https://github.com/Shard-Labs/starknet-devnet/issues/122

## Development related changes

- Introduced mint_lite for qucker mint without transaction and mint with transaction

## Checklist:

- [x] No linter errors
- [ ] Performed a self-review of the code
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [ ] Documented the changes
- [x] Updated the tests
- [ ] All tests are passing

2022-06-30 10:01 UTC, FabijanC requested changes
1. Let's keep the liteness only configurable through the HTTP request (so as it is, no CLI args).
2. Can you try minifying ERC20_Mintable.json? Its size is 4.7 MB, perhaps we could reduce it by:
    - removing whitespaces
    - removing `debug_info` from the json:
        - this would reduce the size as well as remove the paths originating from the computer where it was generated

2022-07-01 07:50 UTC, tabaktoni commented on test/test_fee_token.py
> -
I added imports and removed spaces between imports

2022-07-01 07:51 UTC, tabaktoni commented on test/test_fee_token.py
> +    "3",
How would you test this without seed? Account addresses will be diff every time.
Why is it important not to have devnet arguments?

2022-07-01 11:55 UTC, yoga-braavos commented
@FabijanC @tabaktoni thanks for this.
Can you please give a name, symbol and decimals to the FeeToken (maybe same as TST in alpha-goerli) so connecting Wallets will have something reasonable to show?

2022-07-04 08:31 UTC, FabijanC commented on test/test_fee_token.py
> +    "3",
It's not that it's important not to have devnet arguments, it's just that they serve no purpose (and may lead to confusion). Basically the address used as the target of minting doesn't need to belong to an actually deployed account.

2022-07-04 10:29 UTC, FabijanC commented on starknet_devnet/blueprints/base.py
> +    return jsonify({"new_balance": new_balance, "unit": "wei"})
get_balance doesn't create a transaction so it shouldn't return any tx hashes. But the minting endpoint could.

2022-07-04 10:47 UTC, FabijanC reviewed
Suggestion:
- extra logging will be done in a separate PR
- log token address on startup (this was requested by users)

2022-07-04 14:13 UTC, tabaktoni commented on test/test_fee_token.py
> +    "3",
https://github.com/Shard-Labs/starknet-devnet/pull/143/commits/44e2627bd86867fdbd40170bf6e5f20261eb540b

2022-07-04 14:13 UTC, tabaktoni commented on test/test_fee_token.py
> +    response = requests.post(f"{GATEWAY_URL}/mint", json=json_load)
https://github.com/Shard-Labs/starknet-devnet/pull/143/commits/44e2627bd86867fdbd40170bf6e5f20261eb540b

2022-07-04 14:13 UTC, tabaktoni commented on test/test_fee_token.py
> +def test_mint_lite():
https://github.com/Shard-Labs/starknet-devnet/pull/143/commits/44e2627bd86867fdbd40170bf6e5f20261eb540b

2022-07-04 14:14 UTC, tabaktoni commented on starknet_devnet/fee_token.py
> +        print("original balance value:", response.result.balance)
Will be solved in separate issue

2022-07-04 14:14 UTC, tabaktoni commented on starknet_devnet/fee_token.py
> +        print({'c_address':c_address, 'tx_hash':tx_hash, 'result':result})
will be resolved in separate issue for logging

2022-07-04 14:32 UTC, tabaktoni commented on starknet_devnet/blueprints/base.py
> +    return jsonify({"new_balance": new_balance, "unit": "wei"})
https://github.com/Shard-Labs/starknet-devnet/pull/143/commits/2e27e7fc928bf97884e4c1fb150088aa19b84b99

2022-07-04 15:47 UTC, FabijanC commented on README.md
> +### Mint fee token
We should also have the lite option documented.

2022-07-04 16:03 UTC, merged