/api endpoint to get existing endpoints
Shard-Labs/starknet-devnet pull request #166
Opened 2022-07-07 08:10 UTC by tabaktoni

## Usage related changes

3th party test for existing endpoints

## Checklist:

- [x] No linter errors
- [x] Performed a self-review of the code
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [ ] Documented the changes
- [ ] Linked the issues which this PR resolves
- [ ] Updated the tests
- [x] All tests are passing

2022-07-07 08:31 UTC, FabijanC requested changes
You can add a test for this in the test_endpoints.py file. Doesn't have to be anything strict, but would be good to have something that at least runs the api function.

The PR description says you're adding a "3rd party test for existing endpoints". In what sense is it 3rd party and in what sense is it a test?

2022-07-07 08:31 UTC, FabijanC commented on starknet_devnet/server.py
> +        routes[url.rule] = {}
Can't it be constructed right away, without further assignments, like:
```python
routes[url.rule] = {
  "functionName": ...,
  ...
}
```

2022-07-07 08:31 UTC, FabijanC commented on starknet_devnet/server.py
> +    """Print available endpoints."""
Does it print or return the endpoints?

2022-07-07 12:52 UTC, tabaktoni commented on starknet_devnet/server.py
> +    for url in app.url_map._rules:
WSGI https://werkzeug.palletsprojects.com/en/2.1.x/routing/#werkzeug.routing.Map and used by flask https://wsgi.readthedocs.io/en/latest/frameworks.html

2022-07-07 13:09 UTC, tabaktoni commented
> The PR description says you're adding a "3rd party test for existing endpoints". In what sense is it 3rd party and in what sense is it a test?

As a developer using starknet-devnet in his own project, he can create a test that will check for all existing endpoints that starknet-devnet implements. If starknet-devnet changes some endpoints, his tests will fail and he will know he needs to fix his app for the new version.

2022-07-07 13:26 UTC, tabaktoni commented on starknet_devnet/server.py
> +    for url in app.url_map._rules:
Oh about the response, I am not aware of some sort of existing standard

2022-07-07 14:13 UTC, FabijanC commented on starknet_devnet/server.py
> +    for url in app.url_map._rules:
Instead of disabling protected access linter rule, we could use `app.url_map.iter_rules()`

2022-07-07 14:14 UTC, FabijanC commented on starknet_devnet/server.py
> +        routes[url.rule]["doc"] = app.view_functions[url.endpoint].__doc__
I observed the output that we get for some endpoints. E.g. `/feeder_gateway/get_code` has this value under the `"doc"` property:
```
"\n    Returns the ABI and bytecode of the contract whose contractAddress is provided.\n    "
```
We could `.strip()` the `__doc__`

2022-07-12 15:56 UTC, FabijanC approved these changes
Looks great! Except for the single quotes in the test, but I can do a quick push.

2022-07-12 15:58 UTC, merged