parametrization of test_deploy
Shard-Labs/starknet-devnet pull request #260
Opened 2022-09-08 09:50 UTC by mikiw

## Usage related changes

- Change 1.
- ...

## Development related changes

- Change 1.
- ...

## Checklist:

- [ ] Applied formatting - `./scripts/format.sh`
- [ ] No linter errors - `./scripts/lint.sh`
- [ ] Performed code self-review
- [ ] Rebased to the last commit of the target branch (or merged it into my branch)
- [ ] Documented the changes
- [ ] Linked the issues which this PR resolves
- [ ] Updated the tests
- [ ] All tests are passing

2022-09-12 11:35 UTC, FabijanC requested changes
I'm under a strong impressions that this `test_deploy` test was modeled after `test_general_workflow`. If you look at the old implementation, it's meant to be a light test that doesn't even spawn devnet in background. Could it be rewritten like that again?

2022-09-12 11:35 UTC, FabijanC commented on test/test_deploy.py
>  def get_contract_class():
Can you remove this function? It's only used by a function that could also be removed since it's not used (`get_deploy_transaction`)

2022-09-12 11:35 UTC, FabijanC commented on test/test_deploy.py
> +    assert_transaction_receipt_not_received(NONEXISTENT_TX_HASH)
What's the purpose of this? Can it be removed?

2022-09-12 11:35 UTC, FabijanC commented on test/test_deploy.py
> +    assert_transaction_not_received(NONEXISTENT_TX_HASH)
What's the purpose of this? Can it be removed?

2022-09-12 11:36 UTC, FabijanC commented
Also, would be good to rebase / merge the `master` branch and rerun the tests.

2022-09-15 12:22 UTC, mikiw commented
I'm closing this PR, I'm doing it from scratch on new branch.

2022-09-15 12:22 UTC, closed without merging