Adapt to json RPC v0.2.0
Shard-Labs/starknet-devnet pull request #292
Opened 2022-09-28 13:36 UTC by drknzz

Closes #275 

## Usage related changes

- Adapt to [RPC v0.2.0](https://github.com/starkware-libs/starknet-specs/releases/tag/v0.2.0)
- Adapt tests to transaction v1
- Support `starknet_getNonce` RPC call

## Notes

- `starknet_estimateFee`, which from v0.2.0 should accept [all types of transactions](https://github.com/starkware-libs/starknet-specs/compare/v0.1.0...v0.2.0#diff-dd950cbb7c4a2efb76af2439013e0b1c0fb95b7e0c0fad5113e42e4a45e9b470R440)
  ```
  def estimate_fee(request: RpcBroadcastedTxn, block_id: BlockId)
  ```
  currently does not comply with transactions other than invoke

- Many of the changes come from test cases

## Checklist:

- [x] Applied formatting - `./scripts/format.sh`
- [x] No linter errors - `./scripts/lint.sh`
- [x] Performed code self-review
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [x] Documented the changes
- [x] Linked the issues which this PR resolves
- [x] Updated the tests
- [x] All tests are passing

2022-09-29 14:19 UTC, FabijanC commented
Thanks for the PR! I will not be able to review either this or the next week, only the week after that. But it shouldn't be a rush, since other providers are not yet adapted to v0.2.0, right?

2022-10-05 09:32 UTC, mikiw reviewed
for me looks fine but since it's enormous PR let's wait for @FabijanC

2022-10-17 10:33 UTC, FabijanC requested changes
Looks good, just left some minor comments.

Conflicts need to be resolved. Some of them may be coming from PR #303, but you may keep your changes if you think they are better (because in some cases it might just be that your PR and #303 are implementing the same thing).

2022-10-17 10:33 UTC, FabijanC commented on starknet_devnet/blueprints/rpc/structures/payloads.py
>      signature: List[Felt]
Would it make sense to extract this to a separate type `Signature = List[Felt]` since that's how it is in the specifications?

2022-10-20 15:40 UTC, drknzz commented on test/rpc/test_rpc_transactions.py
> +def pad_zero_entry_points(entry_points: EntryPoints) -> None:
Actually every entry points should be padded according to specs.

2022-10-20 15:40 UTC, drknzz commented on test/rpc/test_rpc_estimate_fee.py
> -def test_estimate_fee_with_complete_request_data(rpc_invoke_tx_common):
Yes, it was testing the same thing.

2022-10-20 15:40 UTC, drknzz commented on test/rpc/test_rpc_class.py
> +EXPECTED_ABI = [
It is abi from the path you gave, but with all `stateMutability` omitted and `constructor` mapped to `function` (as there is no `constructor` type in 0.2.0).

2022-10-20 15:40 UTC, drknzz commented on test/rpc/test_rpc_blocks.py
> -    transaction_hash: str = pad_zero(deploy_info["transaction_hash"])
There were 2 functions `pad_zero` and `rpc_felt`, and the usage of both was twisted, so they've been merged into one function `rpc_felt`.

2022-10-21 09:57 UTC, FabijanC commented on test/rpc/test_rpc_class.py
> +EXPECTED_ABI = [
Ok, can you add a comment explaining that?

2022-10-21 10:00 UTC, FabijanC requested changes
Unfortunately for this PR, new commits are being added to `master` at an unusually high rate, so you need to resolve conflicts again. But other than that, I have no observations, looks good!

2022-10-21 12:07 UTC, FabijanC approved these changes

2022-10-21 12:07 UTC, merged