Allow making RPC calls using block hash or number of a latest block
Shard-Labs/starknet-devnet pull request #313
Opened 2022-10-20 10:22 UTC by cptartur

## Usage related changes

- Currently, in many places in the RPC, it is required that the users uses `"latest"` as block hash/number. With this PR it is also possible to use a `block_hash` or `block_number` if they belong to the latest block.
- This PR allows making calls  with block tag `"pending"` block, though it is still treated as a `"latest"` block (up to discussion if this should be included).
- Changed fixtures using  pytest.mark.parametrize usages with `indirect=True`, to parametrized fixtures.

## Development related changes

None

## Checklist:

- [x] Applied formatting - `./scripts/format.sh`
- [x] No linter errors - `./scripts/lint.sh`
- [x] Performed code self-review
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [x] Documented the changes
- [ ] Linked the issues which this PR resolves
- [x] Updated the tests
- [x] All tests are passing

2022-10-20 11:26 UTC, FabijanC requested changes
Thanks for the contribution!

1. Accepted block IDs can be documented in `page/docs/guide/json-rpc-api.md`.
2. Currently only `"latest"` is tested. Shouldn't providing `"pending"` also be tested?

2022-10-20 11:26 UTC, FabijanC commented on starknet_devnet/blueprints/rpc/utils.py
> +    print(type(block_id), block_id)
print?

2022-10-20 11:26 UTC, FabijanC commented on starknet_devnet/blueprints/rpc/utils.py
> +    last_block = state.starknet_wrapper.blocks.get_last_block()
This last block retrieval can be moved inside of the `if isinstance(block_id, dict)` clause

2022-10-20 11:26 UTC, FabijanC commented on starknet_devnet/blueprints/rpc/utils.py
> +        message="Calls with block_id != 'latest' are not supported currently.",
The error message should also be modified, right? If I may suggest extracting the valid block_ids to a variable and using it for both the actual checking and the message construction.

2022-10-20 12:29 UTC, cptartur commented on starknet_devnet/blueprints/rpc/utils.py
> +        if "block_hash" in block_id:
I think it's not handled anywhere, I'll include a test for this and a proper check.

2022-10-20 12:30 UTC, cptartur commented
1. Will be added
2. I wasn't sure if we want to include "pending", for me it seems like a logical addition since `"pending"` is supported in gateway as far as I know. I'll extend the test to cover pending block.

2022-10-20 13:55 UTC, cptartur commented
Addressed the comments. I've also unchecked "tests are passing" because `test/test_postman.py::test_postman` suddenly stopped working. I suspect it's a problem with some local configuration on my end so if tests could be run on your end we could verify that.

2022-10-21 07:41 UTC, FabijanC requested changes
Cloned your fork, postman test is passing.

2022-10-21 07:41 UTC, FabijanC commented on page/docs/guide/json-rpc-api.md
> +```json
`json` doesn't support comments, so if you could change the language to `js` or `ts`.

2022-10-21 07:41 UTC, FabijanC commented on page/docs/guide/json-rpc-api.md
> +Methods that require a `block_id` only support ids of the `latest` or `pending` block:
Can you point out that these tags refer to the same block?

2022-10-21 07:41 UTC, FabijanC commented on test/rpc/test_rpc_call.py
> +    Call contract with incorrect address
Docstring not corresponding to test.

2022-10-21 07:55 UTC, FabijanC approved these changes

2022-10-21 07:55 UTC, merged