Fix rpc get_events endpoint
Shard-Labs/starknet-devnet pull request #395
Opened 2023-02-10 15:27 UTC by THenry14

## Usage related changes

Fixed some problems with rpc `get_events`:
- `from_block` and `to_block` are now accepted as block_hashes
- fixed `from_block` and `to_block` format in payload, so it now reflects the rpc spec
- fixed problems with response schema validation

There is still a probllem with (in my opinion) a bug in rpc schema regarding Felts (they are in `"^0x0[a-fA-F0-9]{1,63}$"` format, that is different to gateway), that's why I had to wrap test data with `rpc_felt`. From what I know, the discussion is already opened with starkware cairo team to resolve this. 

## Checklist:

- [X] Applied formatting - `./scripts/format.sh`
- [X] No linter errors - `./scripts/lint.sh`
- [X] Performed code self-review
- [X] Rebased to the last commit of the target branch (or merged it into my branch)
- [X] Documented the changes
- [X] Linked the issues which this PR resolves
- [X] Updated the tests
- [X] All tests are passing - `./scripts/test.sh`

2023-02-10 15:36 UTC, FabijanC commented
@THenry14 Thanks for the PR! As you can see, the testing workflows have failed. I will probably review this next week.

2023-02-13 08:00 UTC, THenry14 commented
> @THenry14 Thanks for the PR! As you can see, the testing workflows have failed. I will probably review the PR next week after you have fixed this.

Oh, I'm sorry for that - I have run the linter, but then rebased and missed one unused import. I have addressed that in the newest commit, the tests should pass now :+1:

2023-02-13 11:14 UTC, FabijanC commented
@THenry14
> I can see they failed on "Check out previous test metadata" step, not sure what it does and if it's connected to the code at all

Thanks for fixing the linter issue. What we have now is most likely a CircleCI issue, I will check it out.

2023-02-14 11:04 UTC, FabijanC requested changes
The CircleCI issue doesn't seem to be resolvable from my end. The downloading of previous test results (for splitting between workers) doesn't seem to be executed (file not present in a later check step). I tried writing a report on CircleCI's discussion forum only to get my post marked as spam for providing too many links :rofl: .

Anyway, thank you for raising the quality of Devnet's code, just left some minor comments.

2023-02-14 11:05 UTC, FabijanC commented on starknet_devnet/blueprints/rpc/misc.py
> +    return bool(event.from_address == int(address, 0))
Actually here, what if the address is `None`? That's what has been checked so far. Or it cannot be `None`?

2023-02-14 12:06 UTC, mikiw commented on test/rpc/test_data/get_events.py
> +        rpc_felt("0x99cd8bde557814842a3121e8ddfd433a539b8c9f14bf31ebf108d12e6196e9"),
`0x99cd8bde557814842a3121e8ddfd433a539b8c9f14bf31ebf108d12e6196e9` key was related with some contract that we use to test events. I'll take a look into that.

2023-02-14 12:15 UTC, mikiw commented on test/rpc/test_data/get_events.py
> +        rpc_felt("0x99cd8bde557814842a3121e8ddfd433a539b8c9f14bf31ebf108d12e6196e9"),
Ok, so key is hex for a emited a event name.

2023-02-14 12:18 UTC, mikiw commented on test/rpc/test_data/get_events.py
> +        rpc_felt("0x99cd8bde557814842a3121e8ddfd433a539b8c9f14bf31ebf108d12e6196e9"),
`0x3db3da4221c078e78bd987e54e1cc24570d89a7002cefa33e548d6c72c73f9d` is key for `increase_balance_called` event

2023-02-14 12:22 UTC, mikiw commented on test/rpc/test_data/get_events.py
> +        rpc_felt("0x99cd8bde557814842a3121e8ddfd433a539b8c9f14bf31ebf108d12e6196e9"),
`0x99cd8bde557814842a3121e8ddfd433a539b8c9f14bf31ebf108d12e6196e9` is a key for some event related to fee estimation/charging (I'm not an expert here but I know that some fee estimations are generating event)

2023-02-15 08:31 UTC, THenry14 commented on starknet_devnet/blueprints/rpc/misc.py
> +    return bool(event.from_address == int(address, 0))
My understanding is that it cannot be `None`, but I feel the spec is a bit vague when it goes for required fields, so there is a chance I'm mistaken. I think 0.11 should improve this situation.

2023-02-15 08:31 UTC, THenry14 commented on starknet_devnet/blueprints/rpc/misc.py
> +        (r, e) for r in block.transaction_receipts for e in r.events
Oh, sorry. Thinking about it now, I have no idea why I have named it that way, perhaps I had some brainfart. Changed in newest commit.

2023-02-15 08:32 UTC, THenry14 commented on test/rpc/test_data/get_events.py
> +        rpc_felt("0x99cd8bde557814842a3121e8ddfd433a539b8c9f14bf31ebf108d12e6196e9"),
Sure, moved both events' keys to test.shared in newest commit.

2023-02-15 08:46 UTC, FabijanC approved these changes

2023-02-15 09:02 UTC, merged