Emit LogMessageToL1 event
Shard-Labs/starknet-devnet pull request #468
Opened 2023-05-11 17:45 UTC by FabijanC

## Usage related changes

- Emit `LogMessageToL1` event from `mockSendMessageFromL2` method of `MockMessagintContract` used by Postman in L2->L1 message relaying.

## Development related changes

- Add flag to fail if compilation fails in `compile_contracts.sh`
- Update L1-L2 contracts with content from https://github.com/starkware-libs/cairo-lang/tree/v0.11.0.2/src/starkware/starknet/solidity
- Add assertion of equality of MockStarknetMessaging used in production and in testing.

## Checklist:

- [x] Applied formatting - `./scripts/format.sh`
- [x] No linter errors - `./scripts/lint.sh`
- [x] Performed code self-review
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [x] Documented the changes
- [ ] Linked the issues which this PR resolves
- [x] Updated the tests
- [x] All tests are passing - `./scripts/test.sh`

2023-05-16 14:46 UTC, mikiw requested changes

2023-05-16 14:48 UTC, FabijanC commented on test/contracts/solidity/StarknetMessaging.sol
> +    uint256 constant MAX_L1_MSG_FEE = 1 ether;
My only addition is emitting of the missing event, everything else is copied. The source of the files is in the PR description.

2023-05-16 15:05 UTC, FabijanC commented on test/test_postman.py
> +    assert len(event_filter.get_new_entries()) == 1
good idea, I'm checking

2023-05-16 19:54 UTC, mikiw approved these changes

2023-05-16 19:54 UTC, mikiw approved these changes

2023-05-19 15:31 UTC, FabijanC commented
The user confirms that the solution from this PR helps him.

2023-05-19 15:31 UTC, merged